#!/bin/bash

export theme_black="#000000"
export theme_red="#ff0000"
export theme_green="#38de21"
export theme_yellow="#ffe50a"
export theme_blue="#1460d2"
export theme_purple="#ff005d"
export theme_cyan="#00bbbb"
export theme_white="#bbbbbb"
export theme_brightBlack="#555555"
export theme_brightRed="#f40e17"
export theme_brightGreen="#3bd01d"
export theme_brightYellow="#edc809"
export theme_brightBlue="#5555ff"
export theme_brightPurple="#ff55ff"
export theme_brightCyan="#6ae3fa"
export theme_brightWhite="#ffffff"
export theme_background="#132738"
export theme_foreground="#ffffff"
export theme_cursorColor="#f0cc09"
export theme_selectionBackground="#18354f"
