#!/bin/bash

export theme_black="#3e3e3e"
export theme_red="#970b16"
export theme_green="#07962a"
export theme_yellow="#f8eec7"
export theme_blue="#003e8a"
export theme_purple="#e94691"
export theme_cyan="#89d1ec"
export theme_white="#ffffff"
export theme_brightBlack="#666666"
export theme_brightRed="#de0000"
export theme_brightGreen="#87d5a2"
export theme_brightYellow="#f1d007"
export theme_brightBlue="#2e6cba"
export theme_brightPurple="#ffa29f"
export theme_brightCyan="#1cfafe"
export theme_brightWhite="#ffffff"
export theme_background="#f4f4f4"
export theme_foreground="#3e3e3e"
export theme_cursorColor="#3f3f3f"
export theme_selectionBackground="#a9c1e2"
