#!/bin/bash

export theme_black="#323232"
export theme_red="#d25252"
export theme_green="#7fe173"
export theme_yellow="#ffc66d"
export theme_blue="#4099ff"
export theme_purple="#f680ff"
export theme_cyan="#bed6ff"
export theme_white="#eeeeec"
export theme_brightBlack="#535353"
export theme_brightRed="#f07070"
export theme_brightGreen="#9dff91"
export theme_brightYellow="#ffe48b"
export theme_brightBlue="#5eb7f7"
export theme_brightPurple="#ff9dff"
export theme_brightCyan="#dcf4ff"
export theme_brightWhite="#ffffff"
export theme_background="#323232"
export theme_foreground="#ffffff"
export theme_cursorColor="#d6d6d6"
export theme_selectionBackground="#5b5b5b"
