#!/bin/bash

export theme_black="#4f4f4f"
export theme_red="#ff6c60"
export theme_green="#a8ff60"
export theme_yellow="#ffffb6"
export theme_blue="#96cbfe"
export theme_purple="#ff73fd"
export theme_cyan="#c6c5fe"
export theme_white="#eeeeee"
export theme_brightBlack="#7c7c7c"
export theme_brightRed="#ffb6b0"
export theme_brightGreen="#ceffac"
export theme_brightYellow="#ffffcc"
export theme_brightBlue="#b5dcff"
export theme_brightPurple="#ff9cfe"
export theme_brightCyan="#dfdffe"
export theme_brightWhite="#ffffff"
export theme_background="#000000"
export theme_foreground="#bbbbbb"
export theme_cursorColor="#ffa560"
export theme_selectionBackground="#363983"
