#!/bin/bash

export theme_black="#000000"
export theme_red="#d62e4e"
export theme_green="#71be6b"
export theme_yellow="#beb86b"
export theme_blue="#489bee"
export theme_purple="#e979d7"
export theme_cyan="#6bbeb8"
export theme_white="#d6d6d6"
export theme_brightBlack="#262626"
export theme_brightRed="#e02553"
export theme_brightGreen="#aff08c"
export theme_brightYellow="#dfddb7"
export theme_brightBlue="#65aaf1"
export theme_brightPurple="#ddb7df"
export theme_brightCyan="#b7dfdd"
export theme_brightWhite="#ffffff"
export theme_background="#762423"
export theme_foreground="#ffffff"
export theme_cursorColor="#ffffff"
export theme_selectionBackground="#073642"
