#!/bin/bash

export theme_black="#000000"
export theme_red="#f2777a"
export theme_green="#99cc99"
export theme_yellow="#ffcc66"
export theme_blue="#6699cc"
export theme_purple="#cc99cc"
export theme_cyan="#66cccc"
export theme_white="#ffffff"
export theme_brightBlack="#000000"
export theme_brightRed="#f2777a"
export theme_brightGreen="#99cc99"
export theme_brightYellow="#ffcc66"
export theme_brightBlue="#6699cc"
export theme_brightPurple="#cc99cc"
export theme_brightCyan="#66cccc"
export theme_brightWhite="#ffffff"
export theme_background="#2d2d2d"
export theme_foreground="#cccccc"
export theme_cursorColor="#cccccc"
export theme_selectionBackground="#515151"
