#!/bin/bash

export theme_black="#000000"
export theme_red="#d54e53"
export theme_green="#b9ca4a"
export theme_yellow="#e7c547"
export theme_blue="#7aa6da"
export theme_purple="#c397d8"
export theme_cyan="#70c0b1"
export theme_white="#ffffff"
export theme_brightBlack="#000000"
export theme_brightRed="#d54e53"
export theme_brightGreen="#b9ca4a"
export theme_brightYellow="#e7c547"
export theme_brightBlue="#7aa6da"
export theme_brightPurple="#c397d8"
export theme_brightCyan="#70c0b1"
export theme_brightWhite="#ffffff"
export theme_background="#000000"
export theme_foreground="#eaeaea"
export theme_cursorColor="#eaeaea"
export theme_selectionBackground="#424242"
