#!/bin/bash

export theme_black="#000000"
export theme_red="#ff9da4"
export theme_green="#d1f1a9"
export theme_yellow="#ffeead"
export theme_blue="#bbdaff"
export theme_purple="#ebbbff"
export theme_cyan="#99ffff"
export theme_white="#ffffff"
export theme_brightBlack="#000000"
export theme_brightRed="#ff9da4"
export theme_brightGreen="#d1f1a9"
export theme_brightYellow="#ffeead"
export theme_brightBlue="#bbdaff"
export theme_brightPurple="#ebbbff"
export theme_brightCyan="#99ffff"
export theme_brightWhite="#ffffff"
export theme_background="#002451"
export theme_foreground="#ffffff"
export theme_cursorColor="#ffffff"
export theme_selectionBackground="#003f8e"
