#!/bin/bash

export theme_black="#000000"
export theme_red="#cc6666"
export theme_green="#b5bd68"
export theme_yellow="#f0c674"
export theme_blue="#81a2be"
export theme_purple="#b294bb"
export theme_cyan="#8abeb7"
export theme_white="#ffffff"
export theme_brightBlack="#000000"
export theme_brightRed="#cc6666"
export theme_brightGreen="#b5bd68"
export theme_brightYellow="#f0c674"
export theme_brightBlue="#81a2be"
export theme_brightPurple="#b294bb"
export theme_brightCyan="#8abeb7"
export theme_brightWhite="#ffffff"
export theme_background="#1d1f21"
export theme_foreground="#c5c8c6"
export theme_cursorColor="#c5c8c6"
export theme_selectionBackground="#373b41"
